### ISSUE TITLE
FragmentManager - Weird behavior when orientation/theme changes

### ISSUE THREAD

**Issue by jcalisto** [pevidex/projectPiteu-android-client#104]
Quando se muda a orientação ou se mete em dark mode, os fragmentos ficam todos loucos. 
Isto parece tar relacionado de alguma forma com o bug do boot #91.

**Comment by jcalisto** [comment]
Ver se destruir todos os FragmentManagers no OnDestroy da MainActivity resolve o problema.

**Comment by pevidex** [comment]
Seems like a bad solution but landscape mode was deactivated
