### ISSUE TITLE
Bunch of fixes

### ISSUE THREAD

**Issue by pevidex** [pevidex/projectPiteu-android-client#114]
- [x] botão do olho nas passwords do sign up - zeplin
 - [x] dizer como devem ser as passwords - zeplin
 - [x] ''invalid password'' e ''passwords must match'' warnings devem ser nativos da app e nao android
 - [x] onboarding n deve ter scroll
 - [x] tirar stroke dos botoes
 - [x] por o facebook icon e google icon do mm tamanho
 - [x] 4 passo do onboarding, ter o dropdown como desenhado
 - [x] margens n estão como definido no feed
 - [ ] reduzir utensilios
 - [x] icon de add no search esta estranho (prov pixelizado)
 - [x] icon de my ingredient não fica amarelo quando selecionado
 - [x] icones do tempo e dificuldade da receita estão pixelizados
 - [ ] botão das pessoas na receita n funciona
 - [x] stroke do header e footer da dashboard n está com a cor correta
 - [ ] rever comportamentos das drops no edit profile
 - [x] save no edit profile está esticado
 - [x] caso nao haja possibilidade de adicionar receitas, ter apenas ''Saved recipes'' no perfil
 - [ ] infinite scroll through the app
 - [x] botao de settings enorme
 - [x] list button estranho nos meus ingredientes
 - [x] botão de grid nos meus ingredients ainda está o antigo
 - [x] rever margens nos ingredientes macro das categorias
 - [x] titulos de receitas mudar para preto
 - [x] rever tamanhos dos icons do footer e tamanho do footer

**Comment by jcalisto** [comment]
" por o facebook icon e google icon do mm tamanho" 
Eles têm exactamente o mesmo tamanho, parecem diferentes por ilusão acho eu. 
Vale a pena meter o do face maior só pa parecer igual?

**Comment by pevidex** [comment]
extracting issues to: #137, #138, #139, #136
