### ISSUE TITLE
FeedFragment - Disable My Ingredients Button while loading

### ISSUE THREAD

**Issue by jcalisto** [pevidex/projectPiteu-android-client#132]
To avoid bugs.

**Comment by jcalisto** [comment]
This is not enough to avoid bugs. 
If the user repeatedly clicks My Ingredients, the app will crash due to desync between handleLightRecipes and requestCards.

Should we simplify this flow to use only one call that already returns the info for cards? This would minimize the chance for bugs at the cost of a small increase in data consumption @pevidex

**Comment by pevidex** [comment]
I think blocking the UI until we have a response from the server is way better. We benefit nothing from allowing the user to click multiple times on the MyIngredients button. Changing this now only increases work load.
