### ISSUE TITLE
Updating tables on mobile is not working correctly

### ISSUE THREAD

**Issue by pevidex** [pevidex/projectPiteu-android-client#74]

**Comment by pevidex** [comment]
![image](https://user-images.githubusercontent.com/25803675/88467205-73393280-cecc-11ea-804f-9288dadc2678.png)

**Comment by pevidex** [comment]
@jcalisto testa lá isto. Pode ser limite de requests do heroku e não bug

**Comment by jcalisto** [comment]
@pevidex Esse pedido não é autenticado. Temos limite de 20 pedidos não autenticados por dia.
