### ISSUE TITLE
FeedFragment: when missing ingredients < 2 it comes as null

### ISSUE THREAD

**Issue by pevidex** [pevidex/projectPiteu-android-client#77]
![image](https://user-images.githubusercontent.com/25803675/88477296-be882b00-cf36-11ea-8aad-b13ad62706b6.png)

**Comment by jcalisto** [comment]
```
    public Integer getMissingIngredients() {
        if(missingIngredients <= 1)
            return null;
        return missingIngredients;
    }
```
@pevidex porquê o return null?

**Comment by pevidex** [comment]
Devia ser para não mostrar os missing visto que se não for null não mostra. Altera
